# Use postgres/example user/password credentials
version: '3.1'

services:

  master:
    build:
      context: ./
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-master.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba-master.conf:/var/lib/postgresql/data/pg_hba.conf

  slave:
    build:
      context: ./
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-slave.conf:/etc/postgresql/postgresql.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080